---
title: "elasticlunr.js on V8"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{elasticlunr.js on V8}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  tidy = "styler",
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
if (!require(conifer)) {
  devtools::load_all()
}
library(tibble)
```

## Usage of elasticlunr

#### Add documents to index

```{r}
index <- conifer::elasticlunr()
documents <- tibble::tibble(
    id = c("1", "2", "3"),
    body = c("この木なんの木", "気になる木", "名前も知らない木ですから")
)
index$add(documents)
```

### Search index

```{r}
index$search(c("木", "知らない")) # Default is "OR" search with no expanding.
```

### Update documents in index

```{r}
documents <- tibble::tibble(
    id = c("1", "2"),
    body = c("名前も知らない", "木になるでしょう")
)
index$update(documents)

index$search(c("木", "知らない"))
```

### Remove documents from index

```{r}
documents <- tibble::tibble(
    id = c("3"),
    body = c("名前も知らない木ですから")
)
index$remove(documents)

index$search(c("木", "知らない"))
```

## Related repositories

- [weixsong/elasticlunr.js](https://github.com/weixsong/elasticlunr.js)
- [weixsong/lunr-languages](https://github.com/weixsong/lunr-languages)
